### ISSUE TITLE
HLS audio-only output group

### ISSUE THREAD

**Issue by bbua97** [awsdocs/aws-elemental-mediaconvert-user-guide#11]
Hey there,

I just tried the 13th different configuration for getting a working audio-only hls stream with multiple languages but it doesn't work. Please add an explicit explanation to the mediaconvert user guide. If I follow your docs I get this manifest: 

`#EXTM3U
#EXT-X-VERSION:2
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=96333,AVERAGE-BANDWIDTH=96129,CODECS="mp4a.40.2"
harmonikarallye-besasdesB-Es-As-Des.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=96418,AVERAGE-BANDWIDTH=96130,CODECS="mp4a.40.2"
harmonikarallye-besasdesA-D-G-C.m3u8
`

But with this settings no player detects it as languages. Instead the player handling it with two different video qualities.

**Comment by AWSDocs-Jared** [comment]
Hello,

Thank you for your feedback and I apologize for any frustration this may have caused on your end. I agree that the documentation could be improved for this particular workflow. 

To help show through example, I've attached an example job that takes an MP4 input and outputs an audio-only HLS with two audio tracks tagged with different languages. 

Looking a the job settings, some notable settings include:
Apple HLS Output Group
Two individual audio-only tracks
In the output settings, 'Audio track type' is defined
In the Audio encoding settings, 'Language code' is defined and 'Language code control' is set to Use configured
Other settings are left at their default value, and may vary depending on your workflow

Here's what the resulting parent manifest looks like:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="eng",NAME="englishstream",AUTOSELECT=YES,DEFAULT=YES,URI="indexenglish.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="spa",NAME="spanishstream",AUTOSELECT=YES,DEFAULT=NO,URI="indexspanish.m3u8"
```

Try it out and let me know if you have any questions or anything? Thank you and kind regards.

[audio-only-hls-example.txt](https://github.com/awsdocs/aws-elemental-mediaconvert-user-guide/files/8642958/audio-only-hls-example.txt)
