### ISSUE TITLE
Add AV1 support to docs

### ISSUE THREAD

**Issue by EwoutH** [awsdocs/aws-elemental-mediaconvert-user-guide#3]
> AWS Elemental MediaConvert now offers the ability to encode video using the AV1 (AOMedia Video 1) codec.

Can AV1 support as [announced last week](https://aws.amazon.com/about-aws/whats-new/2020/03/av1-encoding-now-available-with-aws-elemental-mediaconvert/) be added to the docs?

**Comment by EFolsom** [comment]
Apologies! I added it to the HTML docs and forgot to update here. Thanks for the reminder.

It's updated now!
