### ISSUE TITLE
Easy Question for an AWS MEDIACONVERT Pro: CMAF OutputGroupSettings SegmentControl - SEGMENTED_FILES vs SINGLE_FILE

### ISSUE THREAD

**Issue by jaradc** [awsdocs/aws-elemental-mediaconvert-user-guide#8]
When would you use SEGMENTED_FILES instead of SINGLE_FILE and vice-versa?

Are there advantages of choosing one over the other and in what scenarios?

Is there any file size savings? Are there security considerations (is one more "secure" because of multiple files)? Are there any segment loading advantages over another?

```
        "OutputGroupSettings": {
          "Type": "CMAF_GROUP_SETTINGS",
          "CmafGroupSettings": {
            "SegmentLength": 30,
            "Destination": "s3://<BUCKET>/<SOME PATH>/output/",
            "FragmentLength": 3,
            "ImageBasedTrickPlay": "THUMBNAIL",
            "SegmentControl": "SEGMENTED_FILES"
          }
        }
```

Sorry if this is the wrong place to ask this. If I ask a question like this on StackOverflow, they'll ream me a new one.

**Comment by AWSDocs-Jared** [comment]
Thanks for asking this question, and I apologize for the delay in response here.

In general, I would say most customers choose segmented files over a single file output. 

Technically, there may be a small file size saving when outputting a single file, as there will be fewer containers and so some of the container overhead won't have to be repeated. But for most workflows, the difference in total bits should be negligible. 

Instead, consider that segmented files are easier and faster for clients to stream.

AWS recently published some additional resources in this regards you may find helpful, which go into much more detail than I'm able to here: https://docs.aws.amazon.com/wellarchitected/latest/streaming-media-lens/preparation.html

Neither segmentation mode will provide any difference in security over the other. Instead, address security concerns with access, encryption, and DRM.

**Comment by jaradc** [comment]
> Instead, consider that segmented files are easier and faster for clients to stream.

That gives me some benefit around why someone might choose one over the other. I'll keep this in mind! Thank you for replying and expertise.
