### ISSUE TITLE
Job Limitations page contains misleading information around MPEG2 in MXF acceleration

### ISSUE THREAD

**Issue by davemevans** [awsdocs/aws-elemental-mediaconvert-user-guide#9]
`doc_source/job-requirements.md` states that MPEG2 in MXF is eligible for acceleration. This isn't true and jobs submitted with the combination will fail with `Your job settings aren't compatible with accelerated transcoding. Adjust your job settings as follows: [Choose AVC or HEVC as your codec in the following output: [1].]`

**Comment by AWSDocs-Jared** [comment]
Thank you for your feedback. You're correct -- the combination of Accelerated Transcoding (AT) and MXF/MPEG2 outputs is not supported. I will work on updating the table. 
Note only AVC is supported for MXFs when you use AT. Also, MPEG2 is not supported for any container when you use AT.

**Comment by AWSDocs-Jared** [comment]
The Accelerated Transcoding support table has been updated. Thanks again, and let me know if you have any questions or concerns.
